// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLyYUXq_ikxfew7D5rLo8x9zRGXDDMxtY',
    appId: '1:752778089461:web:1ebcc631526c5b859c46bc',
    messagingSenderId: '752778089461',
    projectId: 'city-channel-2b171',
    authDomain: 'city-channel-2b171.firebaseapp.com',
    databaseURL: 'https://city-channel-2b171-default-rtdb.firebaseio.com',
    storageBucket: 'city-channel-2b171.appspot.com',
    measurementId: 'G-0KPC1HM18X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiSHMejKclhMI4hvSFb0PRpR06TgS2Fag',
    appId: '1:752778089461:android:dc39350c1753cb889c46bc',
    messagingSenderId: '752778089461',
    projectId: 'city-channel-2b171',
    databaseURL: 'https://city-channel-2b171-default-rtdb.firebaseio.com',
    storageBucket: 'city-channel-2b171.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzHwRp-pbw1sFkDBs1yngOLhscvPvSu_g',
    appId: '1:752778089461:ios:8f476c2db7c321379c46bc',
    messagingSenderId: '752778089461',
    projectId: 'city-channel-2b171',
    databaseURL: 'https://city-channel-2b171-default-rtdb.firebaseio.com',
    storageBucket: 'city-channel-2b171.appspot.com',
    iosClientId: '752778089461-68dqp6ibv2rts1j8c2thhqlqvis1k1p5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cityChennelWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzHwRp-pbw1sFkDBs1yngOLhscvPvSu_g',
    appId: '1:752778089461:ios:8f476c2db7c321379c46bc',
    messagingSenderId: '752778089461',
    projectId: 'city-channel-2b171',
    databaseURL: 'https://city-channel-2b171-default-rtdb.firebaseio.com',
    storageBucket: 'city-channel-2b171.appspot.com',
    iosClientId: '752778089461-68dqp6ibv2rts1j8c2thhqlqvis1k1p5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cityChennelWeb',
  );
}
